language: python
python:
  - "3.6"
# command to install dependencies
# all needed
install:
  - pip install numpy
  - pip install tada0-toddler-neural-network
  - pip install mnist==0.2.1
  - pip install pypng
  - travis_wait 30 mvn install
  
# command to run tests 
script:
  - python main.py
